@startuml Ticket Management System - Extended Class Diagram

left to right direction

package "Ticket" {
  class TicketController {
    -ticketService: TicketService
    +getAllTickets(): List<TicketDTO>
    +getTicket(id: Long): TicketDTO
    +shareTicket(id: Long, userId: Long): TicketShareDTO
    +unshareTicket(id: Long, userId: Long): void
    +createTicket(ticket: TicketDTO): TicketDTO
    +deleteTicket(id: Long): void
    +updateTicket(id: Long, ticket: TicketDTO): TicketDTO
    +decomposeTicket(ticketId: Long): List<TicketDTO>
  }

  class TicketService {
    -ticketRepository: TicketRepository
    -authService: AuthService
    -isTicketAccessible(Ticket ticket): Boolean
    +getTicketsForCurrentUser(): List<TicketDTO>
    +getTicketById(id: Long): TicketDTO

    +createTicket(ticket: TicketDTO): TicketDTO
    +deleteTicket(id: Long): void
    +updateTicket(id: Long, ticket: TicketDTO): TicketDTO

    +shareTicket(ticketId: Long, userId: Long): TicketShareDTO
    +unshareTicket(ticketId: Long, userId: Long): void

    +decomposeTicket(ticketId: Long): List<TicketDTO>
  }

  interface TicketRepository {
    +findById(id: Long): Ticket
    +findByUserId(userId: Long): List<Ticket>
    +save(ticket: Ticket): Ticket
    +delete(ticket: Ticket): void
  }

  class TicketModel {
    -id: Long
    -title: String
    -description: String
    -status: TicketStatus
    -createdAt: DateTime
    -lastModifiedAt: DateTime
    -dueDate: DateTime
    -DueDateReminder: DueDateReminderModel
    -user: UserModel
    -ticketShares: List<TicketShareModel>
  }

  class TicketShareModel {
    -id: Long
    -ticketId: Long
    -sharedWithId: Long
    -sharedAt: DateTime
  }
  class DueDateReminderModel {
    -id: Long
    -ticketId: Long
    -reminderDate: DateTime
    -isCompleted: Boolean
  }
}


package "User" {
  class UserModel {
    -id: Long
    -email: String
    -username: String
    -userConfig: UserConfigModel
  }
}

UserModel "1" o-- "0..*" TicketModel
TicketModel "1" o-- "0..*" TicketShareModel
UserModel "1..*" o-- "0..*" TicketShareModel
TicketModel "1" o-- "0..1" DueDateReminderModel

TicketModel <.. TicketRepository
TicketService ..> TicketRepository
TicketController ..> TicketService

@enduml