apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iuticket
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Dominik-Gubrynowicz/iu-ticket.git'
    targetRevision: HEAD
    path: kubernetes/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: iuticket
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
